pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk '

- task: NodeTool@0
  displayName: 'Use Node 6.x'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: djangulat-frontend '
  inputs:
    azureSubscription: 'djangulat-frontend - Azure-PublishProfile'
    WebAppName: 'djangulat-frontend'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'djangulat-frontend'
